# Generated by Django 3.0 on 2024-02-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(blank=True, default='Parav1ew!', max_length=64, null=True, verbose_name='姓名'),
        ),
    ]
